name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Repository klonen
        uses: actions/checkout@v4

      - name: Node.js einrichten
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Abhängigkeiten installieren
        run: npm ci

      - name: Sicherheitsüberprüfung (npm audit)
        run: npm audit --audit-level=moderate

      - name: Projekt bauen
        run: npm run build

      - name: Tests ausführen
        run: npm test -- --watch=false --browsers=ChromeHeadless

      - name: Angular & Dependency Update (Dry Run)
        run: npx ng update --all --force --dry-run

      - name: Automatisiertes Update anwenden
        run: npx ng update --all --force --allow-dirty

      - name: Änderungen committen
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "ci: automated dependency updates" || echo "No changes to commit"
          git push || echo "No changes to push"
